config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }

  resources :money_transactions, except: [:edit, :update, :destroy]
  resources :stocks
  resources :stock_items, only: :index
  resources :wallets, only: [:index, :show]

  root 'dashboard#index'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index; end
end

app/views/dashboard/_admin_index.html.slim
.row.font-color-main.mt-4
  .col.col-login.mx-auto
    .text-center.pb-4.pt-4
      b
        .row
          h1 = "Hello, #{current_user.name}."
        .row
          h3 = "Welcome back to Administrator page !"
      br
      = image_tag 'vector/admin-logo.png', style: 'height: 60%; width: 60%;'

app/views/dashboard/_user_index.html.slim
.row.font-color-main.mt-4
  .col.col-login.mx-auto
    .text-center.pb-4.pt-4
      b
        .row
          h1 = "Hello, #{current_user.name}."
        .row
          h3 = "Welcome back to My Wallet!"
      br
      br
      .row.text-center
        .col-6
          = link_to wallet_path(current_user.wallet.id), class: 'dropdown-item' do
            .card.bg-color-info
              .card-body
                = image_tag 'vector/admin-logo.png'
                br
                .super-font.font-color-main.text-center
                  = "Wallet"
        .col-6
          = link_to money_transactions_path, class: 'dropdown-item' do
            .card.bg-color-info
              .card-body
                = image_tag 'vector/second-logo.png'
                br
                .super-font.font-color-main.text-center
                  = "Transaction"
        .col-6
          = link_to new_money_transaction_path(transaction_type: 'buying'), class: 'dropdown-item' do
            .card.bg-color-info
              .card-body
                = image_tag 'vector/fifth-logo.png', style: 'height: 65%; width: 65%;'
                br
                .super-font.font-color-main.text-center
                  = "Buy Stock"
        .col-6
          = link_to new_money_transaction_path(transaction_type: 'selling'), class: 'dropdown-item' do
            .card.bg-color-info
              .card-body
                = image_tag 'vector/fourth-logo.png', style: 'height: 80%; width: 80%;'
                br
                .super-font.font-color-main.text-center
                  = "Sell Stock"

app/views/dashboard/index.html.slim
.container
  .row.m-4
    = render 'shared/flash_messages'
  - if current_user.user_type.eql?('admin')
    = render 'dashboard/admin_index'
  - else
    = render 'dashboard/user_index'