config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }

  resources :money_transactions, except: [:edit, :update, :destroy]
  resources :stocks
  resources :stock_items, only: :index
  resources :wallets, only: [:index, :show]

  root 'dashboard#index'
end

app/views/shared/_flash_messages.html.slim
- if flash[:alert].present?
  .alert.alert-icon.alert-danger role="alert"
    i.fe.fe-alert-triangle.mr-2 aria-hidden="true"
    span.ml-5 = flash[:alert]
- elsif flash[:notice].present?
  .alert.alert-icon.alert-primary role="alert"
    i.fe.fe-bell.mr-2 aria-hidden="true"
    span.ml-5 = flash[:notice]

app/views/shared/_footer.html.slim
footer.footer.bg-color-secondary style='height:80px;'
  .row.align-items-center
    .text-center
      = "All Rights Reserved © 2023 Wallet Management by Dheris Permadi"
  .row
    .text-center
      = "Email: shatrian.permadi@gmail.com | Phone Number: 081221505909"

app/views/shared/_form_error_messages.html.slim
- if selector.errors.full_messages.present?
  .alert.alert-icon.alert-danger.mb-3 role="alert"
    i.fe.fe-alert-triangle.mr-4 aria-hidden="true"
    span.ml-5 = "Warning :"
    br
    #error_explanation
      ul
        - selector.errors.full_messages.each do |message|
          li = message

app/views/shared/_header.html.slim
.header.bg-color-main.py-0
  nav.navbar.navbar-expand-lg
    .container-fluid
      div style='width: 10%;'
        = link_to root_path do
          = image_tag 'vector/third-logo.png', style: 'height: 50%; width: 50%;'
      .text-center
        - if current_user.user_type.eql?('admin')
          button.mx-1.btn.btn-lg.btn-outline-info[type="button"]
            = link_to stocks_path, class: 'dropdown-item' do
              .header-menu = 'Master Stock'
          button.mx-1.btn.btn-lg.btn-outline-info[type="button"]
            = link_to stock_items_path, class: 'dropdown-item' do
              .header-menu = 'Stock Item'
          button.mx-1.btn.btn-lg.btn-outline-info[type="button"]
            = link_to wallets_path, class: 'dropdown-item' do
              .header-menu = 'Wallet'
          button.mx-1.btn.btn-lg.btn-outline-info[type="button"]
            = link_to money_transactions_path, class: 'dropdown-item' do
              .header-menu = 'Money Transaction'
        - else
          button.mx-1.btn.btn-lg.btn-outline-info[type="button"]
            = link_to wallet_path(id: current_user.wallet.id), class: 'dropdown-item' do
              .header-menu = 'Wallet'
          button.mx-1.btn.btn-lg.btn-outline-info[type="button"]
            = link_to stock_items_path, class: 'dropdown-item' do
              .header-menu = 'Stock Item'
          button.mx-1.btn.btn-lg.btn-outline-info[type="button"]
            = link_to money_transactions_path, class: 'dropdown-item' do
              .header-menu = 'Transaction'
      div style='width: 10%;'
        .text-right
          button.btn.btn-sm.btn-danger[type="button"]
            = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
              = "Sign Out"

app/views/shared/failed_message.js.erb
var errors = <%= errors_messages.to_json.html_safe %>;

$("#errors").empty();

for (var i = 0; i < errors.length; i++) {
    $("#errors").append("<div class='alert alert-danger'>" + errors[i] + "</div>");
};

$("#errors").show();